version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: uppulasaikumar
      POSTGRES_PASSWORD: uppulasaikumar
      POSTGRES_DB: mydb
      PGPORT: 5454 
    ports:
      - "5454:5454" 
    networks:
      - my_network

  php:
    image: php:8.2-apache
    container_name: my_php_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
